// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace NetApi.Models
{
    /// <summary>
    /// 权限表
    /// </summary>
    public partial class authorizations
    {
        [Key]
        public int Id { get; set; }
        public int? MenuId { get; set; }
        [StringLength(100)]
        public string AuthType { get; set; }
        public int? TypeId { get; set; }
    }
}