// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

#nullable disable

namespace NetApi.Models
{
    public partial class NetApiContext : DbContext
    {
        public NetApiContext()
        {
        }

        public NetApiContext(DbContextOptions<NetApiContext> options)
            : base(options)
        {
        }

        public virtual DbSet<MiraiBotAuthority> MiraiBotAuthority { get; set; }
        public virtual DbSet<UserMsg> UserMsg { get; set; }
        public virtual DbSet<authorizations> authorizations { get; set; }
        public virtual DbSet<bookmark> bookmark { get; set; }
        public virtual DbSet<company> company { get; set; }
        public virtual DbSet<departments> departments { get; set; }
        public virtual DbSet<menus> menus { get; set; }
        public virtual DbSet<pixiv> pixiv { get; set; }
        public virtual DbSet<positions> positions { get; set; }
        public virtual DbSet<projects> projects { get; set; }
        public virtual DbSet<pxusers> pxusers { get; set; }
        public virtual DbSet<users> users { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.HasCharSet("utf8mb4")
                .UseCollation("utf8mb4_0900_ai_ci");

            modelBuilder.Entity<UserMsg>(entity =>
            {
                entity.HasComment("用户历史消息表");

                entity.Property(e => e.IsRead)
                    .HasDefaultValueSql("'0'")
                    .HasComment("已读：0=未读 1=已读 ");

                entity.Property(e => e.MsgType).HasComment("消息类型：加入=0  纯文本=1  图片=2  断开连接=9");

                entity.Property(e => e.SendDate)
                    .HasDefaultValueSql("CURRENT_TIMESTAMP(6)")
                    .HasComment("发送日期");

                entity.Property(e => e.SenderId).HasComment("发送人Id");

                entity.Property(e => e.SenderName)
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.TargetId).HasComment("接收者Id");
            });

            modelBuilder.Entity<authorizations>(entity =>
            {
                entity.HasComment("权限表");

                entity.Property(e => e.AuthType)
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");
            });

            modelBuilder.Entity<company>(entity =>
            {
                entity.HasComment("所属公司");

                entity.Property(e => e.Name)
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.TexNumber)
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");
            });

            modelBuilder.Entity<departments>(entity =>
            {
                entity.HasComment("部门");

                entity.Property(e => e.Id).HasComment("自增主键");

                entity.Property(e => e.Code)
                    .HasComment("部门编号")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.Name)
                    .HasComment("部门名称")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.ParentId).HasComment("父键");

                entity.Property(e => e.Remarks)
                    .HasComment("备注")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");
            });

            modelBuilder.Entity<menus>(entity =>
            {
                entity.HasComment("菜单");

                entity.Property(e => e.Id).HasComment("菜单自增主键");

                entity.Property(e => e.Name)
                    .HasComment("菜单名称")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");
            });

            modelBuilder.Entity<positions>(entity =>
            {
                entity.HasComment("岗位");

                entity.Property(e => e.Id).HasComment("岗位自增主键");

                entity.Property(e => e.Code)
                    .HasComment("岗位编号")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.Name)
                    .HasComment("岗位名称")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.ParentId).HasComment("父键");

                entity.Property(e => e.Remarks)
                    .HasComment("备注")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");
            });

            modelBuilder.Entity<projects>(entity =>
            {
                entity.HasComment("所属项目");

                entity.Property(e => e.Code)
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.Name)
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");
            });

            modelBuilder.Entity<users>(entity =>
            {
                entity.HasComment("用户");

                entity.Property(e => e.Id).HasComment("自增主键");

                entity.Property(e => e.Account)
                    .HasComment("用户名")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.Name)
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.Pwd)
                    .HasComment("密码")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");

                entity.Property(e => e.Remarks)
                    .HasComment("备注")
                    .UseCollation("utf8_general_ci")
                    .HasCharSet("utf8");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}