// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace NetApi.Models
{
    /// <summary>
    /// 所属项目
    /// </summary>
    public partial class projects
    {
        [Key]
        public int Id { get; set; }
        public int? ParentId { get; set; }
        [StringLength(200)]
        public string Code { get; set; }
        [StringLength(200)]
        public string Name { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        public sbyte? Status { get; set; }
    }
}