// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace NetApi.Models
{
    /// <summary>
    /// 用户
    /// </summary>
    public partial class users
    {
        /// <summary>
        /// 自增主键
        /// </summary>
        [Key]
        public int Id { get; set; }
        /// <summary>
        /// 用户名
        /// </summary>
        [StringLength(100)]
        public string Account { get; set; }
        /// <summary>
        /// 密码
        /// </summary>
        [StringLength(100)]
        public string Pwd { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        public sbyte? Sex { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? Birthday { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(1000)]
        public string Remarks { get; set; }
        public int? CompanyId { get; set; }
        public int? ProjectId { get; set; }
        public int? DeptId { get; set; }
        public int? PositionId { get; set; }
    }
}