// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace NetApi.Models
{
    /// <summary>
    /// 用户历史消息表
    /// </summary>
    public partial class UserMsg
    {
        [Key]
        [StringLength(36)]
        public string Id { get; set; }
        /// <summary>
        /// 发送人Id
        /// </summary>
        [StringLength(100)]
        public string SenderId { get; set; }
        [StringLength(100)]
        public string SenderName { get; set; }
        /// <summary>
        /// 接收者Id
        /// </summary>
        [StringLength(100)]
        public string TargetId { get; set; }
        /// <summary>
        /// 消息类型：加入=0  纯文本=1  图片=2  断开连接=9
        /// </summary>
        public sbyte? MsgType { get; set; }
        [Column(TypeName = "mediumtext")]
        public string Msg { get; set; }
        /// <summary>
        /// 发送日期
        /// </summary>
        [MaxLength(6)]
        public DateTime? SendDate { get; set; }
        /// <summary>
        /// 已读：0=未读 1=已读 
        /// </summary>
        public sbyte? IsRead { get; set; }
    }
}